spring.application.name=allocation
server.port=8082

# Absolute Path to your SQLite DB
spring.datasource.url=jdbc:sqlite:../AgriFleet.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate / JPA Settings
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true